kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: okteto-storage-class
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer